---
# Install Docker on the "Metrics Server" and other pre-configuration
- hosts: nosqlbench
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
    # The next step (downloading NoSQLBecn) may take a while
    # Check file existence to avoid duplicate long-time file downlaod
    - name: Check if NoSQLBench utility already exists
      stat:
        path: "/usr/local/bin/nb"
      register: nb_file

    - name: Download NoSQLBench utility (nb) to "/usr/local/bin" folder and make it executable
      get_url: 
        url : "{{ url_nosqlbench }}"
        dest: "/usr/local/bin"
        mode: '+x'
        owner: "{{ remote_operator_user }}"
        group: "{{ remote_operator_user }}"
      when: nb_file.stat.exists == false

    - name: Install collectd to collect NoSQLBench metrics
      apt: 
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - collectd
        - collectd-utils

    - name: Configure collectd plugins
      copy:
        dest: "/etc/collectd/collectd.conf.d/MyCollectD.conf"
        content: |
            LoadPlugin "logfile"
            <Plugin "logfile">
              LogLevel "info"
              File "/var/log/collectd.log"
              Timestamp true
            </Plugin>

            LoadPlugin network
            <Plugin network>
              Server "localhost" "25826"
            </Plugin>

    - name: Restart collectd service
      service:
        name: collectd
        state: restarted