version: '3'
services:
  database:
    image: "postgres"
    ports:
      - "5432"
    env_file:
      - database.env
    volumes:
      - dbdata:/var/lib/postgresql/data/

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind